### ISSUE TITLE
Add Data Boost

### ISSUE THREAD

**Issue by b141568** [colopl/laravel-spanner#126]
Thank you very much for the project, this is helping a lot.

But will you consider including an option to use Data Boost?
The fact that we can run certain queries without impacting performance is amazing.

Reference:
https://cloud.google.com/spanner/docs/databoost/databoost-overview
https://cloud.google.com/spanner/docs/databoost/databoost-applications?hl=pt-br

**Comment by taka-oyama** [comment]
Yes, this is the issue for it. I'm working on it, and it should be ready sometime this month.

https://github.com/colopl/laravel-spanner/issues/113

**Comment by taka-oyama** [comment]
Closing since PR for data boost was merged https://github.com/colopl/laravel-spanner/pull/131.

Please test it out if possible and let me know what you think.

**Comment by taka-oyama** [comment]
Also, if this project is helping you please consider giving this repo a star. Thanks.
