### ISSUE TITLE
Support auto generating primary key defaults

### ISSUE THREAD

**Issue by taka-oyama** [colopl/laravel-spanner#133]
https://cloud.google.com/spanner/docs/primary-key-default-value

Add something like `autoGenerate()` for INT64 and string columns

**Comment by matthewjumpsoffbuildings** [comment]
This relates to https://github.com/colopl/laravel-spanner/issues/3

Ideally the `increments()` method of Schema builders would also use bit reversed sequences as discussed there

**Comment by matthewjumpsoffbuildings** [comment]
Is there any movement on this?

**Comment by taka-oyama** [comment]
Waiting for [spanner emulator](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator) to implement it so I can test it.

**Comment by matthewjumpsoffbuildings** [comment]
This has been released, as well as Postgres dialect support

https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.12

**Comment by taka-oyama** [comment]
Still waiting for https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/140.
