### ISSUE TITLE
Adding prefix the tables

### ISSUE THREAD

**Issue by b141568** [colopl/laravel-spanner#167]
Hello,

In other database drivers such as pgsql, sqlite and mysql, it is possible to prefix database tables.
It would be interesting if you had this option too.

Eg: config->database.
'connection_name' => [
            'driver' => 'spanner',
            'instance' => 'instance_name',
            'database' => 'database_name',
            'prefix' => 'prefix_',
            ......

**Comment by taka-oyama** [comment]
PR is always welcome.
