### ISSUE TITLE
It doesn't support laravel version 7 or greater

### ISSUE THREAD

**Issue by shailesh-matariya** [colopl/laravel-spanner#17]
Really appreciate your work.

I have tried to install this package in my project running with laravel version 7.21.0. 
It is working fine for laravel 5.6. 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for colopl/laravel-spanner ^3.5 -> satisfiable by colopl/laravel-spanner[v3.5.0].
    - Conclusion: remove symfony/http-kernel v5.1.3
    - Conclusion: don't install symfony/http-kernel v5.1.3
    - colopl/laravel-spanner v3.5.0 requires symfony/cache ^4.3 -> satisfiable by symfony/cache[4.3.x-dev, 4.4.x-dev, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - symfony/cache 4.3.x-dev conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache 4.4.x-dev conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.0 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.0-BETA1 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.0-BETA2 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.0-RC1 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.1 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.10 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.11 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.2 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.3 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.4 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.5 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.6 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.7 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.8 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.3.9 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.0 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.0-BETA1 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.0-BETA2 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.0-RC1 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.1 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.10 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.11 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.2 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.3 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.4 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.5 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.6 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.7 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.8 conflicts with symfony/http-kernel[v5.1.3].
    - symfony/cache v4.4.9 conflicts with symfony/http-kernel[v5.1.3].
    - Installation request for symfony/http-kernel (locked at v5.1.3) -> satisfiable by symfony/http-kernel[v5.1.3].

**Comment by taka-oyama** [comment]
fixed.
https://github.com/colopl/laravel-spanner/commit/2316e0b8e6f3f5d8a10f2ab73780ac6bb2c2a9b7

Please try the latest version v3.5.1.

**Comment by shailesh-matariya** [comment]
It works. Thank you for the quick fix. :+1:
