### ISSUE TITLE
Model relation loading performance

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [colopl/laravel-spanner#195]
If I have a model that has several relations that are loaded with it, I notice that compared to the mysql driver, the performance of loading said model is quite a lot slower.

For example imagine I have a model `Purchase` that has relationships with `User`, `Product`, etc, when running a query to get a page of the `Purchase` models, for each row/instance, a bunch of additional queries are done to get the associated `User` and `Product` models for each `Purchase`.

How is this handled internally? It seems like in the mysql its much more performant, perhaps due to some kind of optimisation that allows multiple queries to be executed in a single request or transaction or something similar? Whereas in the spanner driver it is perhaps doing a series of individual fresh requests/transactions, each incurring a time overhead to initialize and execute?

I haven't dug too much into the internals of how it operates but for starters some info on why this may be so much slower, or possible ways to optimize/batch the related queries, would be great.

I am aware of interleaving but this significant performance difference is happening even on the emulator, on my local machine, with a tiny dataset of say 20 `Purchase` rows, so I don't think thats the primary cause. It seems more similar to the issue I was having with the `DB::pretend()` statements taking so long, due to the time it takes to initialize transactions etc

**Comment by taka-oyama** [comment]
> performance of loading said model is quite a lot slower.

MySQL runs most operations in native C. Cloud Spanner runs mostly in PHP so there's that.

From my personal experience, Spanner is about 10x+ slower than MySQL.
Even when using the emulator its much slower. 
I switch to SQLite's in-memory driver for business logic tests on my local environment because it takes too long.

> It seems like in the mysql its much more performant, perhaps due to some kind of optimisation that allows multiple queries to be executed in a single request or transaction or something similar? 

I don't think they do anything optimization. You can try comparing it yourself by listening to the `QueryExecuted` event and log the actual queries that are being sent to the server.

> for starters some info on why this may be so much slower, or possible ways to optimize/batch the related queries, would be great.

Spanner does authentication and session creation if it doesn't exist that takes up 1~2 seconds.
So the first query will always take a bit longer. You can [warm them up](https://github.com/colopl/laravel-spanner/blob/master/src/Console/WarmupCommand.php) before running the queries to get better results.

Also, make sure you have [these](https://github.com/colopl/laravel-spanner/blob/master/composer.json#L49-L51) extensions installed so you can use sysv for semaphore locking.

**Comment by taka-oyama** [comment]
You should also install the [protobuf extension](https://github.com/colopl/laravel-spanner/blob/master/README.md?plain=1#L15).

**Comment by matthewjumpsoffbuildings** [comment]
> Spanner does authentication and session creation if it doesn't exist that takes up 1~2 seconds.

Does that run per request, or is auth and session handling stored in a cache for some period so that if you have a series of requests you wont incur the 1~2 seconds wait for each subsequent request?

**Comment by taka-oyama** [comment]
[It's stored in the cache.](https://github.com/colopl/laravel-spanner/blob/4d6a97f818d1c22983065c275a3d82b894665618/src/SpannerServiceProvider.php#L110-L129)

**Comment by taka-oyama** [comment]
For context, most select queries in MySQL return in microseconds, where as Spanner takes about 10ms ~ 100ms.

**Comment by matthewjumpsoffbuildings** [comment]
> You should also install the [protobuf extension](https://github.com/colopl/laravel-spanner/blob/master/README.md?plain=1#L15).
On my local dev I have the PECL version of protobuf. Sadly on app engine it seems that the PECL version they provide is incompatible with Spanner so I have to use the PHP only version. However the performance is quite poor both locally and on the server.

> Also, make sure you have [these](https://github.com/colopl/laravel-spanner/blob/master/composer.json#L49-L51) extensions installed so you can use sysv for semaphore locking.
I do have them on local dev, not sure if they are active on app engine

> MySQL runs most operations in native C. Cloud Spanner runs mostly in PHP so there's that.
> From my personal experience, Spanner is about 10x+ slower than MySQL.
> Even when using the emulator its much slower.
This is all quite sad. I understand there is a tradeoff due to Spanner being horizontally scalable, true time etc, but having mostly non-native operations compared to MySQL is disappointing. I wonder are there any plans to improve the operation performance, move any of it to native code etc?

**Comment by taka-oyama** [comment]
> I wonder are there any plans to improve the operation performance, move any of it to native code etc?

I don't think there are any plans. 

[Some parts can be improved](https://github.com/googleapis/google-cloud-php/pull/5700) so I made a feature request, and they are aware of the issue but they haven't gotten around to it yet.

**Comment by matthewjumpsoffbuildings** [comment]
How much of the ~10x increase in query times in Spanner v MySQL is down to serialisation/deserialisation, data type conversion etc, do you think?

And with your proposed feature to allow raw query responses, how much faster do you think that will make things?

**Comment by taka-oyama** [comment]
> How much of the ~10x increase in query times in Spanner v MySQL is due to serialisation/deserialisation, data type conversion etc, do you think?

Depends on how much data you get from the query, but like I mentioned in the issue, it's about 10% but YMMV.

> And with your proposed feature to allow raw query responses, how much faster do you think that will make things?

It's a small improvement compared to the latency of the actual query response im sure. 
It won't match MySQL speeds.
