### ISSUE TITLE
Add Support maxCommitDelay when insert and update

### ISSUE THREAD

**Issue by b141568** [colopl/laravel-spanner#205]
Hello

I noticed that Google recently released capacity-optimized recordings.

We can adjust the maximum writing delay, at the cost of increasing computational usage.

It would be very interesting if it were possible to define a default value in config.database or as a function during the querybuilder.

This can help with systems that need to work with less delay.

Source:
https://cloud.google.com/spanner/docs/throughput-optimized-writes

https://github.com/googleapis/google-cloud-php/blob/e22a5b45bd70c3cc27887d498e7a7d149de86b7b/Spanner/src/Operation.php#L127

**Comment by taka-oyama** [comment]
After #229 is merged, it will be possible to set commit options (which contains `maxCommitDelay`).
