### ISSUE TITLE
phpstan fails on migrations when string('column', 'MAX') is used

### ISSUE THREAD

**Issue by oprudkyi** [colopl/laravel-spanner#218]
spanner supports nonstandard `STRING(MAX)` column def  https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#scalars

in migrations it worked like 
```
$table->string('column', 'MAX');
```

while it works, phpstan fires error 
```
Parameter #2 $length of method Illuminate\Database\Schema\Blueprint::string() expects int|null, string given.
```

while  `@phpstan-ignore-next-line` helps probably some more advanced solution will be more usable

**Comment by taka-oyama** [comment]
One potential way to resolve this is to interpret `-1` as `MAX` so it is compatible with phpdoc.
