### ISSUE TITLE
Installation issue | symfony/cache does not support 6.1 version

### ISSUE THREAD

**Issue by LeVadim** [colopl/laravel-spanner#38]
Hello!

Your package does not support cache version 6.1, could you please bump it up in composer.json?  Thank you!

    - colopl/laravel-spanner[dev-master, v3.6.0, ..., v3.9.2] require symfony/cache ~4|~5 -> found symfony/cache[v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to 6.1.x-dev (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by taka-oyama** [comment]
Hi, thanks for raising the issue. 

This is not possible yet because laravel 8 does not support symfony v6.
I believe it will be supported when laravel 9 is released later this month.

https://github.com/laravel/framework/blob/8.x/composer.json#L36

**Comment by LeVadim** [comment]
Hi @taka-oyama !  It is almost working now.  Currently getting the following error:
ParseError {#1842
  #message: "syntax error, unexpected token "readonly", expecting identifier"
  #code: 0
  #file: "./vendor/google/cloud-spanner/src/V1/TransactionOptions/ReadOnly.php"
  #line: 16
  trace: {
    ./vendor/google/cloud-spanner/src/V1/TransactionOptions/ReadOnly.php:16 { …}
    ./vendor/composer/ClassLoader.php:428 { …}
    ./vendor/google/gax/src/Serializer.php:363 { …}
    ./vendor/google/gax/src/Serializer.php:416 { …}
    ./vendor/google/gax/src/Serializer.php:368 { …}
    ./vendor/google/gax/src/Serializer.php:416 { …}
    ./vendor/google/gax/src/Serializer.php:126 { …}
    ./vendor/google/cloud-spanner/src/Connection/Grpc.php:1192 { …}
    ./vendor/google/cloud-spanner/src/Connection/Grpc.php:790 { …}
    ./vendor/google/cloud-spanner/src/Operation.php:234 { …}

Can you please check it out? Thank you.
@taka-oyama

**Comment by taka-oyama** [comment]
I'm not getting that error in my setup.
That looks error looks like it's coming from google/gax.
Please try updating google/gax to the latest version.

**Comment by LeVadim** [comment]
It does seem like its incompatible with PHP 8.1, that ReadOnly is a reserved name
Sample error - https://github.com/schmittjoh/serializer/issues/1331

Whom would you suggest reaching out to regarding this issue? Thank you.
@taka-oyama

**Comment by LeVadim** [comment]
I have created a thread with gax-php
Link is here - https://github.com/googleapis/gax-php/issues/374

**Comment by taka-oyama** [comment]
Hi, thanks for the update. From what I can tell from looking at the issue you raised at google/gax, it seems like readonly became a reserved word in 8.1. Looking at the errors, I think this might be something [google/cloud-spanner](https://github.com/googleapis/google-cloud-php) needs to fix by renaming their class.

**Comment by taka-oyama** [comment]
I raised the issue in google-cloud-php. Hopefully they will fix it soon.

**Comment by taka-oyama** [comment]
Seems like we're finally getting some progress.
https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0

> Fix: add missing reserved classnames (https://github.com/protocolbuffers/protobuf/pull/9458)
> PHP 8.1 compatibility (https://github.com/protocolbuffers/protobuf/pull/9370)

Unfortunately there is a problem building 3.20.0 (https://github.com/protocolbuffers/protobuf/pull/9727) in pecl so we'll have to wait until that's resolved as well.

**Comment by taka-oyama** [comment]
Status update.

https://github.com/protocolbuffers/protobuf/releases/tag/v21.0

Protobuf v21.0 was released. Now all we need is a fix on google-cloud-php (https://github.com/googleapis/google-cloud-php/issues/5129) side and we would be able to update to PHP 8.1 which Symfony 6.1 requires.

**Comment by taka-oyama** [comment]
Seems like https://github.com/googleapis/google-cloud-php/issues/5129 was fixed in `google/cloud-spanner 1.51.0`.
I updated to php 8.1 and the tests seems to pass fine. 

So running `composer update google/cloud-spanner` should make everything work (Including symfony cache v6.1).

Please check it out.

**Comment by taka-oyama** [comment]
I will close this for now since my environment is working under PHP 8.1 / Symfony 6.1.

Please reopen if you continue to encounter errors.
