### ISSUE TITLE
Issue while connecting to cloud spanner

### ISSUE THREAD

**Issue by vaidhyanathan93** [colopl/laravel-spanner#44]
Using php8.0 and laravel9. 

I am trying to connect to my cloud spanner instance. but getting some SQL error. I am running Cloud spanner in the postgres mode. 

The php artisan migrate also failed. But I ran manually. 

<img width="1728" alt="Screen Shot 2022-11-01 at 7 56 58 PM" src="https://user-images.githubusercontent.com/3818495/199257329-ffaa1d17-6ec1-40ac-9fc9-73d72641bdfe.png">

**Comment by taka-oyama** [comment]
You're probably getting that error because spanner's identifiers are escaped with `` ` `` where as postgres uses `"`.

Unfortunately, this library only supports Google's Standard SQL.

Was there a problem with using postgres' driver?

**Comment by vaidhyanathan93** [comment]
Thanks , that works
